rpkid/rpki/gui/app/urls.py
# Copyright (C) 2010, 2011  SPARTA, Inc. dba Cobham Analytic Solutions
# Copyright (C) 2012  SPARTA, Inc. a Parsons Company
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND SPARTA DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL SPARTA BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

__version__ = '$Id$'

from django.conf.urls import patterns, url
from rpki.gui.app import views

urlpatterns = patterns(
    '',
    (r'^$', views.dashboard),
    url(r'^alert/$', views.AlertListView.as_view(), name='alert-list'),
    url(r'^alert/clear_all$', views.alert_clear_all, name='alert-clear-all'),
    url(r'^alert/(?P<pk>\d+)/$', views.AlertDetailView.as_view(),
        name='alert-detail'),
    url(r'^alert/(?P<pk>\d+)/delete$', views.AlertDeleteView.as_view(),
        name='alert-delete'),
    (r'^conf/export$', views.conf_export),
    (r'^conf/list$', views.conf_list),
    (r'^conf/select$', views.conf_select),
    url(r'^conf/export_asns$', views.export_asns, name='export-asns'),
    url(r'^conf/export_prefixes$', views.export_prefixes, name='export-prefixes'),
    url(r'^conf/import_asns$', views.import_asns, name='import-asns'),
    url(r'^conf/import_prefixes$', views.import_prefixes, name='import-prefixes'),
    (r'^parent/import$', views.parent_import),
    (r'^parent/(?P<pk>\d+)/$', views.parent_detail),
    (r'^parent/(?P<pk>\d+)/delete$', views.parent_delete),
    (r'^parent/(?P<pk>\d+)/export$', views.parent_export),
    (r'^child/import$', views.child_import),
    (r'^child/(?P<pk>\d+)/$', views.child_detail),
    (r'^child/(?P<pk>\d+)/add_address$', views.child_add_prefix),
    (r'^child/(?P<pk>\d+)/add_asn$', views.child_add_asn),
    (r'^child/(?P<pk>\d+)/delete$', views.child_delete),
    (r'^child/(?P<pk>\d+)/edit$', views.child_edit),
    (r'^child/(?P<pk>\d+)/export$', views.child_response),
    url(r'^gbr/create$', views.ghostbuster_create, name='gbr-create'),
    url(r'^gbr/(?P<pk>\d+)/$', views.GhostbusterDetailView.as_view(), name='gbr-detail'),
    url(r'^gbr/(?P<pk>\d+)/edit$', views.ghostbuster_edit, name='gbr-edit'),
    url(r'^gbr/(?P<pk>\d+)/delete$', views.ghostbuster_delete, name='gbr-delete'),
    (r'^refresh$', views.refresh),
    (r'^client/import$', views.client_import),
    (r'^client/$', views.client_list),
    (r'^client/(?P<pk>\d+)/$', views.client_detail),
    (r'^client/(?P<pk>\d+)/delete$', views.client_delete),
    url(r'^client/(?P<pk>\d+)/export$', views.client_export, name='client-export'),
    (r'^repo/import$', views.repository_import),
    (r'^repo/(?P<pk>\d+)/$', views.repository_detail),
    (r'^repo/(?P<pk>\d+)/delete$', views.repository_delete),
    (r'^resource_holder/$', views.resource_holder_list),
    (r'^resource_holder/create$', views.resource_holder_create),
    (r'^resource_holder/(?P<pk>\d+)/delete$', views.resource_holder_delete),
    (r'^resource_holder/(?P<pk>\d+)/edit$', views.resource_holder_edit),
    (r'^roa/(?P<pk>\d+)/$', views.roa_detail),
    (r'^roa/create$', views.roa_create),
    (r'^roa/create_multi$', views.roa_create_multi),
    (r'^roa/confirm$', views.roa_create_confirm),
    (r'^roa/confirm_multi$', views.roa_create_multi_confirm),
    url(r'^roa/export$', views.roa_export, name='roa-export'),
    url(r'^roa/import$', views.roa_import, name='roa-import'),
    (r'^roa/(?P<pk>\d+)/delete$', views.roa_delete),
    url(r'^roa/(?P<pk>\d+)/clone$', views.roa_clone, name="roa-clone"),
    (r'^route/$', views.route_view),
    (r'^route/(?P<pk>\d+)/$', views.route_detail),
    url(r'^route/suggest$', views.route_suggest, name="suggest-roas"),
    (r'^user/$', views.user_list),
    (r'^user/create$', views.user_create),
    (r'^user/(?P<pk>\d+)/delete$', views.user_delete),
    (r'^user/(?P<pk>\d+)/edit$', views.user_edit),
)

rpkid/rpki/gui/app/forms.py
# Copyright (C) 2010, 2011  SPARTA, Inc. dba Cobham Analytic Solutions
# Copyright (C) 2012  SPARTA, Inc. a Parsons Company
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND SPARTA DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL SPARTA BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

__version__ = '$Id$'


from django.contrib.auth.models import User
from django import forms
from rpki.resource_set import (resource_range_as, resource_range_ip)
from rpki.gui.app import models
from rpki.exceptions import BadIPResource
from rpki.POW import IPAddress


class AddConfForm(forms.Form):
    handle = forms.CharField(required=True,
            help_text='your handle for your rpki instance')
    run_rpkid = forms.BooleanField(required=False, initial=True,
            label='Run rpkid?',
            help_text='do you want to run your own instance of rpkid?')
    rpkid_server_host = forms.CharField(initial='rpkid.example.org',
            label='rpkid hostname',
            help_text='publicly visible hostname for your rpkid instance')
    rpkid_server_port = forms.IntegerField(initial=4404,
            label='rpkid port')
    run_pubd = forms.BooleanField(required=False, initial=False,
            label='Run pubd?',
            help_text='do you want to run your own instance of pubd?')
    pubd_server_host = forms.CharField(initial='pubd.example.org',
            label='pubd hostname',
            help_text='publicly visible hostname for your pubd instance')
    pubd_server_port = forms.IntegerField(initial=4402, label='pubd port')
    pubd_contact_info = forms.CharField(initial='repo-man@rpki.example.org',
            label='Pubd contact',
            help_text='email address for the operator of your pubd instance')


class GhostbusterRequestForm(forms.ModelForm):
    """
    Generate a ModelForm with the subset of parents for the current
    resource handle.
    """
    # override default form field
    parent = forms.ModelChoiceField(queryset=None, required=False,
            help_text='Specify specific parent, or none for all parents')

    #override
    issuer = forms.ModelChoiceField(queryset=None, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        conf = kwargs.pop('conf')
        # override initial value for conf in case user tries to alter it
        initial = kwargs.setdefault('initial', {})
        initial['issuer'] = conf
        super(GhostbusterRequestForm, self).__init__(*args, **kwargs)
        self.fields['parent'].queryset = conf.parents.all()
        self.fields['issuer'].queryset = models.Conf.objects.filter(pk=conf.pk)

    class Meta:
        model = models.GhostbusterRequest
        exclude = ('vcard', 'given_name', 'family_name', 'additional_name',
                   'honorific_prefix', 'honorific_suffix')

    def clean(self):
        email = self.cleaned_data.get('email_address')
        postal = self.cleaned_data.get('postal_address')
        telephone = self.cleaned_data.get('telephone')
        if not any([email, postal, telephone]):
            raise forms.ValidationError(
                'One of telephone, email or postal address must be specified')

        return self.cleaned_data


class ImportForm(forms.Form):
    """Form used for uploading parent/child identity xml files."""
    handle = forms.CharField(required=False,
                             widget=forms.TextInput(attrs={'class': 'xlarge'}),
                             help_text='Optional.  Your name for this entity, or blank to accept name in XML')
    xml = forms.FileField(label='XML file')


class ImportRepositoryForm(forms.Form):
    handle = forms.CharField(max_length=30, required=False,
                             label='Parent Handle',
                             help_text='Optional.  Must be specified if you use a different name for this parent')
    xml = forms.FileField(label='XML file')


class ImportClientForm(forms.Form):
    """Form used for importing publication client requests."""
    xml = forms.FileField(label='XML file')


class ImportCSVForm(forms.Form):
    csv = forms.FileField(label='CSV file')


class UserCreateForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.CharField(max_length=30,
                            help_text='email address for new user')
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label='Confirm Password')
    resource_holders = forms.ModelMultipleChoiceField(
        queryset=models.Conf.objects.all(),
        help_text='allowed to manage these resource holders'

    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('user already exists')
        return username

    def clean(self):
        p1 = self.cleaned_data.get('password')
        p2 = self.cleaned_data.get('password2')
        if p1 != p2:
            raise forms.ValidationError('passwords do not match')
        return self.cleaned_data


class UserEditForm(forms.Form):
    """Form for editing a user."""
    email = forms.CharField()
    pw = forms.CharField(widget=forms.PasswordInput, label='Password',
                         required=False)
    pw2 = forms.CharField(widget=forms.PasswordInput, label='Confirm password',
                          required=False)
    resource_holders = forms.ModelMultipleChoiceField(
        queryset=models.Conf.objects.all(),
        help_text='allowed to manage these resource holders'
    )

    def clean(self):
        p1 = self.cleaned_data.get('pw')
        p2 = self.cleaned_data.get('pw2')
        if p1 != p2:
            raise forms.ValidationError('Passwords do not match')
        return self.cleaned_data


class ROARequest(forms.Form):
    """Form for entering a ROA request.

    Handles both IPv4 and IPv6."""

    prefix = forms.CharField(
        widget=forms.TextInput(attrs={
            'autofocus': 'true', 'placeholder': 'Prefix',
            'class': 'span4'
        })
    )
    max_prefixlen = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Max len',
            'class': 'span1'
        })
    )
    asn = forms.IntegerField(
        widget=forms.TextInput(attrs={
            'placeholder': 'ASN',
            'class': 'span1'
        })
    )
    confirmed = forms.BooleanField(widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        """Takes an optional `conf` keyword argument specifying the user that
        is creating the ROAs.  It is used for validating that the prefix the
        user entered is currently allocated to that user.

        """
        conf = kwargs.pop('conf', None)
        kwargs['auto_id'] = False
        super(ROARequest, self).__init__(*args, **kwargs)
        self.conf = conf
        self.inline = True
        self.use_table = False

    def _as_resource_range(self):
        """Convert the prefix in the form to a
        rpki.resource_set.resource_range_ip object.

        If there is no mask provided, assume the closest classful mask.

        """
        prefix = self.cleaned_data.get('prefix')
        if '/' not in prefix:
            p = IPAddress(prefix)

            # determine the first nonzero bit starting from the lsb and
            # subtract from the address size to find the closest classful
            # mask that contains this single address
            prefixlen = 0
            while (p != 0) and (p & 1) == 0:
                prefixlen = prefixlen + 1
                p = p >> 1
            mask = p.bits - (8 * (prefixlen / 8))
            prefix = prefix + '/' + str(mask)

        return resource_range_ip.parse_str(prefix)

    def clean_asn(self):
        value = self.cleaned_data.get('asn')
        if value < 0:
            raise forms.ValidationError('AS must be a positive value or 0')
        return value

    def clean_prefix(self):
        try:
            r = self._as_resource_range()
        except:
            raise forms.ValidationError('invalid prefix')

        manager = models.ResourceRangeAddressV4 if r.version == 4 else models.ResourceRangeAddressV6
        if not manager.objects.filter(cert__conf=self.conf,
                                      prefix_min__lte=r.min,
                                      prefix_max__gte=r.max).exists():
            raise forms.ValidationError('prefix is not allocated to you')
        return str(r)

    def clean_max_prefixlen(self):
        v = self.cleaned_data.get('max_prefixlen')
        if v:
            if v[0] == '/':
                v = v[1:]  # allow user to specify /24
            try:
                if int(v) < 0:
                    raise forms.ValidationError('max prefix length must be positive or 0')
            except ValueError:
                raise forms.ValidationError('invalid integer value')
        return v

    def clean(self):
        if 'prefix' in self.cleaned_data:
            r = self._as_resource_range()
            max_prefixlen = self.cleaned_data.get('max_prefixlen')
            max_prefixlen = int(max_prefixlen) if max_prefixlen else r.prefixlen()
            if max_prefixlen < r.prefixlen():
                raise forms.ValidationError(
                    'max prefix length must be greater than or equal to the prefix length')

rpkid/rpki/gui/app/templates/app/alert_detail.html
{% extends "app/app_base.html" %}
{% load url from future %}
{% load app_extras %}

{% block content %}
<div class="page-header">
  <h1>Alert Detail <small>{{ object.subject }}</small></h1>
</div>

<div class="row-fluid">
<table class="table">
  <tr>
    <th>Date:</th><td> {{ object.when }}</td>
  </tr>
  <tr>
    <th>Severity:</th><td><span class="label {% severity_class object.severity %}">{{ object.get_severity_display }}</span></td>
  </tr>
</table>

<p>
{{ object.text }}

</div>

{% block action %}
<div class="row-fluid">
<a class="btn btn-danger" title="delete this alert" href="{% url "alert-delete" object.pk %}"><i class="icon-trash"></i> Delete</a>
</div>
{% endblock action %}

{% endblock content %}

rpkid/rpki/gui/app/templates/app/alert_list.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class="page-header">
  <h1>Alerts</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Subject</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr {% if not obj.seen %}style="font-weight: bold" {% endif %}class="{% if obj.severity == 1 %}warning{% endif %} {% if obj.severity == 2 %}error{% endif %}">
      <td>{# <input type="checkbox"> #}</td>
      <td>{{ obj.when }}</td>
      <td><a href="{{ obj.get_absolute_url }}" title="view text of alert">{{ obj.subject }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class='row-fluid'>
  <a class="btn btn-danger" href="{% url 'alert-clear-all' %}"><i class='icon-trash'></i> Delete All</a>
</div>
{% endblock content %}

rpkid/rpki/gui/app/templates/app/bootstrap_form.html
{% if form.non_field_errors %}
<div class="alert alert-block alert-error">
  {{ form.non_field_errors }}
</div>
{% endif %}

{% for field in form %}

{% if field.is_hidden %}
{{ field }}
{% else %}
<div class="control-group {% if field.errors %}error{% endif %}">
	<label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
  <div class="controls">
    {{ field }}
    {% if field.help_text %}
    <span class="help-inline">{{ field.help_text }}</span>
    {% endif %}
    {% if field.errors %}
    <span class="help-inline">{{ field.errors }}</span>
    {% endif %}
  </div>
</div>
{% endif %}

{% endfor %}

rpkid/rpki/gui/app/templates/app/child_detail.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class="page-header">
  <h1>Child: {{ object.handle }}</h1>
</div>

<div class='row-fluid'>
    <p><strong>Valid until</strong> {{ object.valid_until }}
</div>

<div class='row-fluid'>
  <div class='span6'>
    <strong>Addresses</strong>
    {% if object.address_ranges.all %}
    <ul class='unstyled'>
      {% for a in object.address_ranges.all %}
      <li>{{ a.as_resource_range }}</li>
      {% endfor %}
    </ul>
    {% else %}
    <p style='font-style:italic'>none</p>
    {% endif %}
  </div>
  <div class='span6'>
    <strong>ASNs</strong>
    {% if object.asns.all %}
    <ul class='unstyled'>
    {% for a in object.asns.all %}
    <li>{{ a.as_resource_range }}</li>
    {% endfor %}
    </ul>
    {% else %}
    <p style='font-style:italic'>none</p>
    {% endif %}
  </div>
</div>

{% block action %}
<a class='btn' href="{% url "rpki.gui.app.views.child_edit" object.pk %}" title='Edit this child'><i class="icon-edit"></i> Edit</a>
<a class='btn' href="{% url "rpki.gui.app.views.child_add_asn" object.pk %}" title='Delegate an ASN to this child'><i class="icon-plus-sign"></i> AS</a>
<a class='btn' href="{% url "rpki.gui.app.views.child_add_prefix" object.pk %}" title='Delegate a prefix to this child'><i class="icon-plus-sign"></i> Prefix</a>
<a class='btn' href="{% url "rpki.gui.app.views.child_response" object.pk %}" title='Download XML file to send to child'><i class="icon-download"></i> Export</a>
<a class="btn" href="{% url "rpki.gui.app.views.child_delete" object.pk %}" title="Delete this child"><i class="icon-trash"></i> Delete</a>
{% endblock %}

{% endblock %}

rpkid/rpki/gui/app/templates/app/conf_empty.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}

{% if request.user.is_superuser %}
<div class="alert alert-info">
There are currently no resource holders on this system.
</div>
<a class="btn" href="{% url "rpki.gui.app.views.resource_holder_create" %}" title="create a new resource holder"><i class="icon-plus-sign"></i> Create</a>
{% else %}
<div class="alert alert-error">
Your account does not have permission to manage any resource handles on this server.  Please contact your portal-gui adminstrator.
</div>
{% endif %}

{% endblock %}

rpkid/rpki/gui/app/templates/app/conf_list.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class="page-header">
  <h1>Handle List</h1>
</div>

<p>Please select a handle.</p>

<ul>
  {% for c in conf_list %}
  <li><a href="{% url "rpki.gui.app.views.conf_select" %}?handle={{ c.handle }}&next={{ next_url }}">{{ c.handle }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

rpkid/rpki/gui/app/templates/app/ghostbusterrequest_detail.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class="page-header">
  <h1>Ghostbuster Request</h1>
</div>

<table class='table table-striped table-condensed'>
  <tr><td>Full Name</td><td>{{ object.full_name }}</td></tr>

  {% if object.honorific_prefix %}
  <tr><td >Honorific Prefix</td><td>{{ object.honorific_prefix }}</td></tr>
  {% endif %}

  {% if object.organization %}
  <tr><td >Organization</td><td>{{ object.organization }}</td></tr>
  {% endif %}

  {% if object.telephone %}
  <tr><td >Telephone</td><td>{{ object.telephone }}</td></tr>
  {% endif %}

  {% if object.email_address %}
  <tr><td >Email</td><td>{{ object.email_address }}</td></tr>
  {% endif %}

  {% if object.box %}
  <tr><td >P.O. Box</td><td>{{ object.box }}</td></tr>
  {% endif %}

  {% if object.extended %}
  <tr><td >Extended Address</td><td>{{ object.extended }}</td></tr>
  {% endif %}

  {% if object.street %}
  <tr><td >Street Address</td><td>{{ object.street }}</td></tr>
  {% endif %}

  {% if object.city %}
  <tr><td >City</td><td>{{ object.city }}</td></tr>
  {% endif %}

  {% if object.region %}
  <tr><td >Region</td><td>{{ object.region }}</td></tr>
  {% endif %}

  {% if object.code %}
  <tr><td >Postal Code</td><td>{{ object.code }}</td></tr>
  {% endif %}

  {% if object.country %}
  <tr><td >Country</td><td>{{ object.country }}</td></tr>
  {% endif %}

</table>

{% block action %}
{# the roarequest_confirm_delete template will override this section #}
<a class="btn" href="{% url "gbr-edit" object.pk %}"><i class="icon-edit"></i> Edit</a>
<a class="btn" href="{% url "gbr-delete" object.pk %}"><i class="icon-trash"></i> Delete</a>
{% endblock action %}

{% endblock content %}

rpkid/rpki/gui/app/templates/app/import_parent_form.html
{% extends "app/app_base.html" %}

{% block content %}

<div class='page-header'>
  <h1>Import Parent</h1>
</div>

<form enctype="multipart/form-data" method="POST" action="{{ request.get_full_path }}">
  {% csrf_token %}
  {% include "app/bootstrap_form.html" %}
  <div class='actions'>
    <input class='btn primary' type="submit" value="Import">
    <a class='btn' href="{% url rpki.gui.app.views.parent_list %}">Cancel</a>
  </div>
</form>

{% endblock content %}

<!-- vim: set sw=2: -->

rpkid/rpki/gui/app/templates/app/import_pubclient_form.html
{% extends "base.html" %}

{% block content %}

<form enctype="multipart/form-data" method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <table>
{{ form.as_table }}
</table>
<input type="submit" value="Import">
</form>

{% endblock %}

rpkid/rpki/gui/app/templates/app/import_repository_form.html
{% extends "base.html" %}

{% block content %}

<form enctype="multipart/form-data" method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <table>
{{ form.as_table }}
</table>
<input type="submit" value="Import">
</form>

{% endblock %}

rpkid/rpki/gui/app/templates/app/repository_detail.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class="page-header">
  <h1>Repository: {{ object.handle }}</h1>
</div>

<table class="table">
  <tr>
    <td><strong>SIA</strong></td>
    <td>{{ object.sia_base }}</td>
  </tr>
</table>

{% block action %}
<a class="btn" href="{% url "rpki.gui.app.views.repository_delete" object.pk %}" title="Delete this repository"><i class="icon-trash"></i> Delete</a>
{% endblock action %}
{% endblock content %}

rpkid/rpki/gui/app/templates/app/roarequest_confirm_form.html
{% extends "app/app_base.html" %}
{% load url from future %}

{% block content %}
<div class='page-title'>
  <h1>Confirm ROA Request</h1>
</div>

<div class='row-fluid'>
  <div class='span6'>
    <div class='alert alert-block-message alert-warning'>
      <p><strong>Please confirm</strong> that you would like to create the following ROA.
      The accompanying table indicates how the validation status may change as a result.
    </div>

    <table class='table table-condensed table-striped'>
      <tr>
	<th>AS</th>
	<th>Prefix</th>
	<th>Max Length</th>
      </tr>
      <tr>
	<td>{{ asn }}</td>
	<td>{{ prefix }}</td>
	<td>{{ max_prefixlen }}</td>
      </tr>
    </table>

    <form method='POST' action='{% url "rpki.gui.app.views.roa_create_confirm" %}'>
      {% csrf_token %}
      {% include "app/bootstrap_form.html" %}

      <div class='form-actions'>
	<input class='btn btn-primary' type='submit' value='Create'/>
	<a class='btn' href='{% url "rpki.gui.app.views.dashboard" %}'>Cancel</a>
      </div>
    </form>
  </div>

  <div class='span6'>
    <h2>Matched Routes</h2>

    <table class='table table-striped table-condensed'>
      <tr>
        <th>Prefix</th>
        <th>Origin AS</th>
        <th>Validation Status</th>
      </tr>
      {% for r in routes %}
      <tr>
        <td>{{ r.get_prefix_display }}</td>
        <td>{{ r.asn }}</td>
        <td><span class='label {{ r.status_label }}'>{{ r.status }}</span></td>
      </tr>
      {% endfor %}
    </table>
  </div>

</div>
{% endblock content %}

rpkid/rpki/gui/app/templates/app/roarequest_form.html
{% extends "app/app_base.html" %}
{% load url from future %}

{# This form is used for creating a new ROA request #}

{% block content %}
<div class='page-title'>
  <h1>Create ROA</h1>
</div>

<script src='{{ STATIC_URL }}js/jquery-1.8.3.min.js'></script>
<script type='text/javascript'>
  var f = function(){
    var e = $("#route_table")
    e.empty()
    e.append('<tr><th>Prefix</th><th>AS</th></tr>')
    $.getJSON('/api/v1/route/', {'prefix__in':$(this).val()}, function(data){
      if (data.length == 1) {
	$("#id_asn").val(data[0].asn)
      }
      for (var x in data) {
	e.append('<tr><td>' + data[x].prefix + '</td><td>' + data[x].asn + '</td></tr>')
      }
    })
  }

  $(document).ready(function(){ $("#id_prefix").change(f) })
</script>

<div class='row-fluid'>
  <div class='span6'>
    <form method='POST' action='{{ request.get_full_path }}'>
      {% csrf_token %}
      {% include "app/bootstrap_form.html" %}
      <div class="form-actions">
	<input class="btn" type="submit" value="Preview">
	<a class="btn" href="{% url "rpki.gui.app.views.dashboard" %}">Cancel</a>
      </div>
    </form>
  </div>

  <div class='span6'>
    Routes matching your prefix:
    <table class='table table-condensed table-striped' id='route_table'>
      <tr><th>Prefix</th><th>AS</th></tr>
      <!-- script above populates this table based upon prefix matches -->
    </table>
  </div>
</div><!--row-->
{% endblock content %}