rpkid/rpki/gui/cacheview/urls.py
# Copyright (C) 2011  SPARTA, Inc. dba Cobham Analytic Solutions
# Copyright (C) 2013  SPARTA, Inc. a Parsons Company
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND SPARTA DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL SPARTA BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

__version__ = '$Id$'

from django.conf.urls import patterns, url
from rpki.gui.cacheview.views import (CertDetailView, RoaDetailView,
                                      GhostbusterDetailView)

urlpatterns = patterns('',
    url(r'^search$', 'rpki.gui.cacheview.views.search_view',
        name='res-search'),
    url(r'^cert/(?P<pk>[^/]+)$', CertDetailView.as_view(), name='cert-detail'),
    url(r'^gbr/(?P<pk>[^/]+)$', GhostbusterDetailView.as_view(),
        name='ghostbuster-detail'),
    url(r'^roa/(?P<pk>[^/]+)$', RoaDetailView.as_view(), name='roa-detail'),
    (r'^$', 'rpki.gui.cacheview.views.global_summary'),
)

# vim:sw=4 ts=8 expandtab

rpkid/rpki/gui/cacheview/models.py
# Copyright (C) 2011  SPARTA, Inc. dba Cobham Analytic Solutions
# Copyright (C) 2012  SPARTA, Inc. a Parsons Company
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND SPARTA DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL SPARTA BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

__version__ = '$Id$'

from datetime import datetime
import time

from django.db import models
from django.core.urlresolvers import reverse

import rpki.resource_set
import rpki.gui.models


class TelephoneField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 255
        models.CharField.__init__(self, *args, **kwargs)


class AddressRange(rpki.gui.models.PrefixV4):
    @models.permalink
    def get_absolute_url(self):
        return ('rpki.gui.cacheview.views.addressrange_detail', [str(self.pk)])


class AddressRangeV6(rpki.gui.models.PrefixV6):
    @models.permalink
    def get_absolute_url(self):
        return ('rpki.gui.cacheview.views.addressrange_detail_v6',
                [str(self.pk)])


class ASRange(rpki.gui.models.ASN):
    @models.permalink
    def get_absolute_url(self):
        return ('rpki.gui.cacheview.views.asrange_detail', [str(self.pk)])

kinds = list(enumerate(('good', 'warn', 'bad')))
kinds_dict = dict((v, k) for k, v in kinds)


class ValidationLabel(models.Model):
    """
    Represents a specific error condition defined in the rcynic XML
    output file.
    """
    label = models.CharField(max_length=79, db_index=True, unique=True)
    status = models.CharField(max_length=255)
    kind = models.PositiveSmallIntegerField(choices=kinds)

    def __unicode__(self):
        return self.label


class RepositoryObject(models.Model):
    """
    Represents a globally unique RPKI repository object, specified by its URI.
    """
    uri = models.URLField(unique=True, db_index=True)

generations = list(enumerate(('current', 'backup')))
generations_dict = dict((val, key) for (key, val) in generations)


class ValidationStatus(models.Model):
    timestamp = models.DateTimeField()
    generation = models.PositiveSmallIntegerField(choices=generations, null=True)
    status = models.ForeignKey(ValidationLabel)
    repo = models.ForeignKey(RepositoryObject, related_name='statuses')


class SignedObject(models.Model):
    """
    Abstract class to hold common metadata for all signed objects.
    The signing certificate is ommitted here in order to give a proper
    value for the 'related_name' attribute.
    """
    repo = models.ForeignKey(RepositoryObject, related_name='cert', unique=True)

    # on-disk file modification time
    mtime = models.PositiveIntegerField(default=0)

    # SubjectName
    name = models.CharField(max_length=255)

    # value from the SKI extension
    keyid = models.CharField(max_length=60, db_index=True)

    # validity period from EE cert which signed object
    not_before = models.DateTimeField()
    not_after = models.DateTimeField()

    def mtime_as_datetime(self):
        """
        convert the local timestamp to UTC and convert to a datetime object
        """
        return datetime.utcfromtimestamp(self.mtime + time.timezone)

    def status_id(self):
        """
        Returns a HTML class selector for the current object based on its validation status.
        The selector is chosen based on the current generation only.  If there is any bad status,
        return bad, else if there are any warn status, return warn, else return good.
        """
        for x in reversed(kinds):
            if self.repo.statuses.filter(generation=generations_dict['current'], status__kind=x[0]):
                return x[1]
        return None  # should not happen

    def __unicode__(self):
        return u'%s' % self.name


class Cert(SignedObject):
    """
    Object representing a resource certificate.
    """
    addresses = models.ManyToManyField(AddressRange, related_name='certs')
    addresses_v6 = models.ManyToManyField(AddressRangeV6, related_name='certs')
    asns = models.ManyToManyField(ASRange, related_name='certs')
    issuer = models.ForeignKey('self', related_name='children', null=True)
    sia = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse('cert-detail', args=[str(self.pk)])

    def get_cert_chain(self):
        """Return a list containing the complete certificate chain for this
        certificate."""
        cert = self
        x = [cert]
        while cert != cert.issuer:
            cert = cert.issuer
            x.append(cert)
        x.reverse()
        return x
    cert_chain = property(get_cert_chain)


class ROAPrefix(models.Model):
    "Abstract base class for ROA mixin."

    max_length = models.PositiveSmallIntegerField()

    class Meta:
        abstract = True

    def as_roa_prefix(self):
        "Return value as a rpki.resource_set.roa_prefix_ip object."
        rng = self.as_resource_range()
        return self.roa_cls(rng.min, rng.prefixlen(), self.max_length)

    def __unicode__(self):
        p = self.as_resource_range()
        if p.prefixlen() == self.max_length:
            return str(p)
        return '%s-%s' % (str(p), self.max_length)


# ROAPrefix is declared first, so subclass picks up __unicode__ from it.
class ROAPrefixV4(ROAPrefix, rpki.gui.models.PrefixV4):
    "One v4 prefix in a ROA."

    roa_cls = rpki.resource_set.roa_prefix_ipv4

    @property
    def routes(self):
        """return all routes covered by this roa prefix"""
        return RouteOrigin.objects.filter(prefix_min__gte=self.prefix_min,
                                          prefix_max__lte=self.prefix_max)

    class Meta:
        ordering = ('prefix_min',)


# ROAPrefix is declared first, so subclass picks up __unicode__ from it.
class ROAPrefixV6(ROAPrefix, rpki.gui.models.PrefixV6):
    "One v6 prefix in a ROA."

    roa_cls = rpki.resource_set.roa_prefix_ipv6

    class Meta:
        ordering = ('prefix_min',)


class ROA(SignedObject):
    asid = models.PositiveIntegerField()
    prefixes = models.ManyToManyField(ROAPrefixV4, related_name='roas')
    prefixes_v6 = models.ManyToManyField(ROAPrefixV6, related_name='roas')
    issuer = models.ForeignKey('Cert', related_name='roas')

    def get_absolute_url(self):
        return reverse('roa-detail', args=[str(self.pk)])

    class Meta:
        ordering = ('asid',)

    def __unicode__(self):
        return u'ROA for AS%d' % self.asid


class Ghostbuster(SignedObject):
    full_name = models.CharField(max_length=40)
    email_address = models.EmailField(blank=True, null=True)
    organization = models.CharField(blank=True, null=True, max_length=255)
    telephone = TelephoneField(blank=True, null=True)
    issuer = models.ForeignKey('Cert', related_name='ghostbusters')

    def get_absolute_url(self):
        # note that ghostbuster-detail is different from gbr-detail! sigh
        return reverse('ghostbuster-detail', args=[str(self.pk)])

    def __unicode__(self):
        if self.full_name:
            return self.full_name
        if self.organization:
            return self.organization
        if self.email_address:
            return self.email_address
        return self.telephone


from rpki.gui.routeview.models import RouteOrigin

rpkid/rpki/gui/cacheview/forms.py
# Copyright (C) 2011  SPARTA, Inc. dba Cobham Analytic Solutions
# Copyright (C) 2013  SPARTA, Inc. a Parsons Company
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND SPARTA DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS.  IN NO EVENT SHALL SPARTA BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

__version__ = '$Id$'

from django import forms

from rpki.gui.cacheview.misc import parse_ipaddr
from rpki.exceptions import BadIPResource
from rpki.resource_set import resource_range_as


class SearchForm(forms.Form):
    asn = forms.CharField(required=False, help_text='AS or range', label='AS')
    addr = forms.CharField(required=False, max_length=40, help_text='range/CIDR', label='IP Address')

    def clean(self):
        asn = self.cleaned_data.get('asn')
        addr = self.cleaned_data.get('addr')
        if (asn and addr) or ((not asn) and (not addr)):
            raise forms.ValidationError, 'Please specify either an AS or IP range, not both'

        if asn:
            try:
                resource_range_as.parse_str(asn)
            except ValueError:
                raise forms.ValidationError, 'invalid AS range'

        if addr:
            #try:
            parse_ipaddr(addr)
            #except BadIPResource:
            #    raise forms.ValidationError, 'invalid IP address range/prefix'

        return self.cleaned_data


class SearchForm2(forms.Form):
    resource = forms.CharField(required=True)

rpkid/rpki/gui/cacheview/templates/cacheview/addressrange_detail.html
{% extends "cacheview/cacheview_base.html" %}

{% block content %}
<h1>{% block title %}IP Range Detail{% endblock %}</h1>

<p>
IP Range: {{ object }}
</p>

<p>Covered by the following resource certs:</p>

<ul>
{% for cert in object.certs.all %}
<li><a href="{{ cert.get_absolute_url }}">{{ cert }}</a></li>
{% endfor %}
</ul>

{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/cacheview_base.html
{% extends "base.html" %}
{% load url from future %}

{% block sidebar %}
<form method='post' action='{% url 'res-search' %}'>
  {% csrf_token %}
  <input type='text' id='id_resource' name='resource' placeholder='prefix or AS'>
  <button type='submit'>Search</button>
</form>
{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/cert_detail.html
{% extends "cacheview/signedobject_detail.html" %}

{% block title %}
Resource Certificate Detail
{% endblock %}

{% block detail %}

<h2>RFC3779 Resources</h2>

<table class='table table-striped'>
  <thead>
    <tr><th>AS Ranges</th><th>IP Ranges</th></tr>
  </thead>
  <tbody>
    <tr>
        <td style='text-align:left;vertical-align:top'>
            <ul class='compact'>
                {% for asn in object.asns.all %}
                <li><a href="{{ asn.get_absolute_url }}">{{ asn }}</a></li>
                {% endfor %}
            </ul>
        </td>
        <td style='text-align:left;vertical-align:top'>
            <ul class='compact'>
                {% for rng in object.addresses.all %}
                <li><a href="{{ rng.get_absolute_url }}">{{ rng }}</a></li>
                {% endfor %}
            </ul>
        </td>
    </tr>
  </tbody>
</table>

<div class='section'>
<h2>Issued Objects</h2>
<ul>

{% if object.ghostbusters.all %}
    <li>
<h3>Ghostbusters</h3>

<table class='table table-striped'>
  <thead>
    <tr><th>Name</th><th>Expires</th></tr>
  </thead>
  <tbody>

{% for g in object.ghostbusters.all %}
    <tr class='{{ g.status_id }}'>
        <td><a href="{{ g.get_absolute_url }}">{{ g }}</a></td>
        <td>{{ g.not_after }}</td>
    </tr>
  </tbody>
{% endfor %}

</table>
{% endif %}

{% if object.roas.all %}
        <li>
<h3>ROAs</h3>
<table class='table table-striped'>
  <thead>
    <tr><th>#</th><th>Prefix</th><th>AS</th><th>Expires</th></tr>
  </thead>
  <tbody>
    {% for roa in object.roas.all %}
    {% for pfx in roa.prefixes.all %}
    <tr class='{{ roa.status_id }}'>
        <td><a href="{{ roa.get_absolute_url }}">#</a></td>
        <td>{{ pfx }}</td>
        <td>{{ roa.asid }}</td>
        <td>{{ roa.not_after }}</td>
    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if object.children.all %}
<li>
<h3>Children</h3>
<table class='table table-striped'>
  <thead>
    <tr><th>Name</th><th>Expires</th></tr>
  </thead>
  <tbody>

    {% for child in object.children.all %}
    <tr class='{{ child.status_id }}'>
        <td><a href="{{ child.get_absolute_url }}">{{ child.name }}</a></td>
        <td>{{ child.not_after }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

</ul>

</div><!--issued objects-->

{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/ghostbuster_detail.html
{% extends "cacheview/signedobject_detail.html" %}

{% block title %}Ghostbuster Detail{% endblock %}

{% block detail %}
<p>
<table class='table'>
    <tr><td>Full Name</td><td>{{ object.full_name }}</td></tr>
    <tr><td>Organization</td><td>{{ object.organization }}</td></tr>
    <tr><td>Email</td><td>{{ object.email_address }}</td></tr>
    <tr><td>Telephone</td><td>{{ object.telephone }}</td></tr>
</table>
{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/global_summary.html
{% extends "cacheview/cacheview_base.html" %}

{% block content %}
<div class='page-header'>
  <h1>Browse Global RPKI</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Expires</th>
			<th>URI</th>
		</tr>
	</thead>
	<tbody>
		{% for r in roots %}
		<tr>
		  <td><a href="{{ r.get_absolute_url }}">{{ r.name }}</a></td>
		    <td>{{ r.not_after }}</td>
		    <td>{{ r.repo.uri }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock content %}

rpkid/rpki/gui/cacheview/templates/cacheview/query_result.html
{% extends "cacheview/cacheview_base.html" %}

{% block content %}

<h1>{% block title %}Query Results{% endblock %}</h1>

<table>
    <tr><th>Prefix</th><th>AS</th><th>Valid</th><th>Until</th></tr>
    {% for object in object_list %}
    <tr class='{{ object.1.status.kind_as_str }}'>
        <td>{{ object.0 }}</td>
        <td>{{ object.1.asid }}</td>
        <td><a href="{{ object.1.get_absolute_url }}">{{ object.1.ok }}</a></td>
        <td>{{ object.1.not_after }}</td>
    </tr>
    {% endfor %}
</table>

<p><a href="{% url rpki.gui.cacheview.views.query_view %}">new query</a></p>

{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/roa_detail.html
{% extends "cacheview/signedobject_detail.html" %}

{% block title %}ROA Detail{% endblock %}

{% block detail %}
<p>
<table>
    <tr><td>AS</td><td>{{ object.asid }}</td></tr>
</table>

<h2>Prefixes</h2>

<ul>
{% for pfx in object.prefixes.all %}
<li>{{ pfx }}
{% endfor %}
</ul>
{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/search_form.html
{% extends "cacheview/cacheview_base.html" %}

{% block title %}
{{ search_type }} Search
{% endblock %}

{% block content %}

<h1>{{search_type}} Search</h1>

<form method='post' action='{{ request.url }}'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' name='Search'>
</form>

{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/search_result.html
{% extends "cacheview/cacheview_base.html" %}

{% block content %}

<div class='page-header'>
  <h1>Search Results <small>{{ resource }}</small></h1>
</div>

<h2>Matching Resource Certificates</h2>
{% if certs %}
<ul>
{% for cert in certs %}
<li><a href="{{ cert.get_absolute_url }}">{{ cert }}</a>
{% endfor %}
</ul>
{% else %}
<p>none</p>
{% endif %}

<h2>Matching ROAs</h2>
{% if roas %}
<table class='table table-striped'>
  <thead>
    <tr>
      <th>#</th><th>Prefix</th><th>AS</th>
    </tr>
  </thead>
  <tbody>
{% for roa in roas %}
<tr>
  <td><a href="{{ roa.get_absolute_url }}">#</a></td>
  <td>{{ roa.prefixes.all.0 }}</td>
  <td>{{ roa.asid }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>none</p>
{% endif %}

{% endblock %}

rpkid/rpki/gui/cacheview/templates/cacheview/signedobject_detail.html
{% extends "cacheview/cacheview_base.html" %}

{% block content %}
<div class='page-header'>
<h1>{% block title %}Signed Object Detail{% endblock %}</h1>
</div>

<h2>Cert Info</h2>
<table class='table table-striped'>
    <tr><td>Subject Name</td><td>{{ object.name }}</td></tr>
    <tr><td>SKI</td><td>{{ object.keyid }}</td></tr>
    {% if object.sia %}
    <tr><td>SIA</td><td>{{ object.sia }}</td></tr>
    {% endif %}
    <tr><td>Not Before</td><td>{{ object.not_before }}</td></tr>
    <tr><td>Not After</td><td>{{ object.not_after }}</td></tr>
</table>

<h2>Metadata</h2>

<table class='table table-striped'>
    <tr><td>URI</td><td>{{ object.repo.uri }}</td></tr>
    <tr><td>Last Modified</td><td>{{ object.mtime_as_datetime|date:"DATETIME_FORMAT" }}</td></tr>
</table>

<h2>Validation Status</h2>
<table class='table table-striped'>
  <thead>
    <tr><th>Timestamp</th><th>Generation</th><th>Status</th></tr>
  </thead>
  <tbody>
    {% for status in object.repo.statuses.all %}
    <tr class="{{ status.status.get_kind_display }}"><td>{{ status.timestamp }}</td><td>{{ status.get_generation_display }}</td><td>{{ status.status.status }}</td></tr>
    {% endfor %}
  </tbody>
</table>

<h2>X.509 Certificate Chain</h2>

<table class='table table-striped'>
  <thead>
    <tr><th>Depth</th><th>Name</th></tr>
  </thead>
  <tbody>

{% for cert in chain %}
<tr class='{{ cert.1.status_id }}'>
    <td>{{ cert.0 }}</td>
    <td><a href="{{ cert.1.get_absolute_url }}">{{ cert.1.name }}</a></td>
</tr>
{% endfor %}
</tbody>

</table>

{% block detail %}{% endblock %}

{% endblock %}